### ISSUE TITLE
RGBW / RGBWW

### ISSUE THREAD

**Issue by vKnmnn** [EspLight/EspLight-PCB#2]
Thanks for publishing this project. i printed a few of these boards, and it works really well.

What do you think of an alternate version with 4 and 5 channels for RGBW and RGBWW strips? could you make that?

**Comment by michielbrink** [comment]
Hi,
Awesome to hear people are still using it. Unfortunately I don't have the time to design more PCBs for free right now.

,
Michiel
https://mlhelectronics.com
